FROM eclipse/che-theia:0.3.18-nightly
RUN apk add --update --no-cache gdb
RUN curl -L -o /default-theia-plugins/cpptools-linux.vsix https://github.com/Microsoft/vscode-cpptools/releases/download/0.21.0/cpptools-linux.vsix
