id: org.eclipse.che.editor.theia
version: 1.0.1
type: Che Editor
name: theia-ide
title: Eclipse Theia for Eclipse Che
description: Eclipse Theia
icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
url: https://github.com/olexii4/che7-plugins/releases/download/1.0.1/che-editor-plugin.tar.gz