publisher: stayfool
apiVersion: v2
id: stayfool.vscode-asciidoc
version: 2.7.6
type: VS Code extension
name: AsciiDoc
title: AsciiDoc
description: AsciiDoc Support, and code browsing https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
spec:
  extensions:
  - https://github.com/olexii4/che7-plugins/releases/download/1.0.1/asciidoctor-vscode-2.7.6.vsix